stages:
  - build
  - test
  - publish

compile scala sources:
  stage: build
  script:
    - sbt test:compile

sbt test:
  stage: test
  script:
    - sbt coverage test coverageReport
  services:
    - redis:5.0.3
  variables:
    REDIS_HOST: redis

publish on bintray:
  stage: publish
  only:
    - master
  script:
    - sbt -Dbintray.user=gitlab-ci -Dbintray.pass=$BINTRAY_API_KEY publish

image: hseeberger/scala-sbt:11.0.3_1.2.8_2.12.8
variables:
  SBT_OPTS: "-Dsbt.global.base=sbt-cache/sbtboot -Dsbt.boot.directory=sbt-cache/boot -Dsbt.ivy.home=sbt-cache/ivy"
  COURSIER_CACHE: "sbt-cache/coursier"
cache:
  key: "sbt-$CI_BUILD_REF_NAME"
  paths:
    - sbt-cache

before_script:
  - gpg --import <(echo "$GITLAB_PGP_PRIVATE_KEY") && source <(gpg -q --decrypt secrets-env.sh.secret)
