include:
  - 'https://colisweb-open-source.gitlab.io/ci-common/v13.10.0/templates/scala.yml'


compile scala-distances:
  extends:
    - .sbt-compile-cross
  tags: []

test scala-distances:
  extends:
  - .sbt-test-cross
  - .redis
  tags: []

version:
  extends: .version
  tags: []

publish on sonatype:
  extends: .sonatype-publish
  tags: []
