include:
  - 'https://gitlab.com/colisweb-open-source/ci-common/raw/v9.4.2/templates/scala.yml'
  - 'https://gitlab.com/colisweb-open-source/ci-common/raw/v9.4.2/services/redis.yml'

test scala-distances:
  extends:
  - .sbt-test
  - .redis
  tags: []

version:
  extends: .version
  tags: []

publish on bintray:
  extends: .bintray-publish
  tags: []
