include:
  - 'https://gitlab.com/colisweb-open-source/ci-common/raw/v12.4.7/templates/scala.yml'
  - 'https://gitlab.com/colisweb-open-source/ci-common/raw/v12.4.7/services/redis.yml'

compile scala-distances:
  extends:
    - .sbt-compile-cross
  tags: []

test scala-distances:
  extends:
  - .sbt-test-cross
  - .redis
  tags: []

version:
  extends: .version
  tags: []

publish on bintray:
  extends: .bintray-publish
  tags: []
