sudo: false
services:
- redis-server
language: scala
scala:
- 2.11.12
- 2.12.6
script:
- sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport
jdk:
- oraclejdk8
before_install:
- if [ $TRAVIS_PULL_REQUEST = 'false' ]; then
    openssl aes-256-cbc -K $encrypted_ff9678f33741_key -iv $encrypted_ff9678f33741_iv -in travis/secrets.tar.enc -out travis/local.secrets.tar -d;
    tar xv -C travis -f travis/local.secrets.tar;
  fi
after_success:
  - if [ $TRAVIS_PULL_REQUEST = 'false' ]; then
      sbt ++$TRAVIS_SCALA_VERSION releaseEarly;
    fi
  - bash <(curl -s https://codecov.io/bash)
deploy:
  on:
    tags: true
env:
  global:
  - secure: TBNoQkd7TUJksC3iCNtGFp3HNLQFkSldyoqU84T9XbxC07iluOC219LQnevQ6oGzngvJgteUT/1WR+WMTbrLKh+Xti0IwMYTbxPsOIA4FMKEqMbYfNdUJdrBmGExvJYX6uUCefVI85UWCeB8rFcHYTTXlyLvVUWkHljG6Wdk4Y8xIwfhs7Y/CF8s7RTsy/ellhvFEGtQgOPIXk2QP1VKEloFkI4N44EPYjT52ea6Ih4Z60pJYQE01Rt9ZmNmbFt06qe7IWiyyn6iPoEv+ZaSOgIsDCbwT7EEQhTv00KQr0Zsj1g80NSB3S+wkm+5dhA0zn5An8UjCgSPkuI6BLyzjDaMvUcKsBhZIyxLlsL38XmrncVg06yT4BA5KVsWJCZlgGIPiJk8NfDbHXBJDUMwf4mn/y2eTuE6odt1X1aGy7PpvC96yOnrpM7jVEoV7aEMjntuWXfHUQyrUs3zT9qIycIlZAF72PyaaY+oAAqonw+4nEqAWKgPE7mJt5VXGXGg8r/5c1mndD9LiO08THCQDZ/ZS0c2a6IGdho20+5HL1vsxSFJpLz+tEW7AYs1vjofs3lMeInVR/dvJHfwpsoxAEXxsafqZVS6492oN7vcHtbqT3VKMpqheySViECG42/J66UFzaCxwTCHJpZ2IDGozJuGmC8BIb3i40UgulVLxg8=
  - secure: eiAa6xuP1sC11rVbwdyiNbv9qiceRMRGhPUCM75DqcXU6zK7gQ72ioz4Bl8Zl7H8ZsCIVUJ6YFyCh6Mr+cXIl02285SjbiPekKiNSqGUbkFLad2pzsN3fONOqwOCJjFDOwnVZFxSklDmIj/nz0v0c5sq3AKtXSB0yDd2OIxNnE9LiGT1tWwp4sgXs6dr848mNX05csMYSlmHwsrDYqBApXBV0h9yVS9Zxr0p9uGzhakS/LksAhRxPuf4tvFTWb4MrFh7yuz86Z74wVyobr6ceUtLohTaz2uN6vqNRoYNqawkVGfxYRcyLVMq8InNen/+Z3dcnhCGk7mg8DB2YAvgMD7qvU1UKtTP1pjBIM8EREmUMVuvpfXOCE9ZlwVAad3j/15YBzVz/8GjRYZNXugf4m6MsFPBceVNs46417oqN7BnBmPsKtamX92xAtQMlSmtB/UbQa8NwKsXezn0jjAGdqxQjWwIe5JsqMfyYRNF5PlfzOLyqVTiMTitNAbD9NeTCsP3uLzFopihURZSGbzCe1g6AmuuYOSjeGQ0zG3x06/+O+SWfWHZ5c+jHO1BD31YOgCrOW2339+7oo0LbB4g/VxNl2TbG5GY5uGnBsd45qjr3Gp2hS6YSU1wYg8d2EuJxPNUXyJAK+CHbou9gcDNlJ9cNh0q8pkoSSaniFEy5RU=
  - secure: U+abKxZiKM7HurlodK24a8KEzJ6hL0rbxqzprTjwGTAG2LmTAMQARcpcOK6hMjxxp6uhO+BtAYq4z86r0f5wCT78+ImJYiUOIRrKduI99w5bT9cW5SR0nLp9kDEUbrY2xC9rc9+8UAWExRcMCBL1q+4Sl+XQjnv6fax6KNt6prZwc/7knpHqBbgj7vwtBFBNojVi6F+sLit2D4lr96jIPdTktK11Z9ohLwytIoHS0+gzIf/q2ogKcRzcdFs696yOVPLYiywPtJGQyX34OH+ZM9/I6HAqx/VbgZrGE9Y5wR5sAhb5HXTGb6j6QK9rlXQnwCvxmrJlmMBU/98pHCVoEuR7puqBIfI/UhEQSxMuaGFYoGeWbXJW1nH2+e5iTWNCXgNmA/oGQSbduVAjPoSFQ72O82C/Fc1fm7gW3VFbWiXGWN1r/CwCSOBOuQWRzMOhfMZII9tWR6gLyIYjTzJThzqizek2n/GKkBuPeKMO65aFr4fuND1iAE+UfIb5B/I99E8tr+v/gjZgAlWCMeq0AsWn6Q3/aO+bD3xQr7HYNk67HAynV4MusF1hzxH+U6OFu4ohXvadHdSTMW5/VhscfJchxfgAj67FoRzEgYtb/TBPjdDoUpwsumCEq2XnTCRqeWrbeolZYGjB5IXAK8pDepn7X1vou4mzr2qC6faOWRU=
  - secure: pJQ6VtTjzZBeOw14bKDpi3YBtee3l/VERAaR/bnFfVEXkNqREYb82yZoA2WQXcBSsCsxLdmxak6v6Sqlyq8hqMQGPbGUOMmro4QV0VDm8GuGVg80yETOZilxIbMlrVcv8jz7T5IfYugKvnovosOgwjTeRXa/NkOmdfdV2TN54tUjFLiGMXzSetxAXoQE60+v63d+ppGyVyxFAw7Xu8pUqfGvcGH+4u42NuSMIqT7iXlynbg3BIAg4x9AWZ9SwrGh3YzMErhch36N5IX4uvHbeRp85JWOPvrTqZqxebzN33QdM1edWbbcklcmsf5iKq54a3Nnms0HQ3Tx/ja+ef34xhm+TZH0Iew6UGUI/M2oroGp1h/YPZPtGg2QDeLWRVdm8A3q3EFUb1+nBZM0reDd+kTKvnx6uYQ4HD3d4khpyTFrTdY4HejlvOj3WUUFRqx89ULsN2tzTXMCYCrA74Y3zT0Q65G+W8Z6JcPKF4FCkDnudql2ILpyVKRVr0JEfSYOd5cA3dlUgtLQs1rTCx434EqCPooar7pHEFHQf2whr8rttEiL0ee5hC21Wf3Zqq/FnSaMS10nw7VuE1KvsU4XuHHt24CKd+xx+ACJ/K+/OvHdeEl/chov51+NoHAjrHBwY1HHA78RdoIgcP5IxqxzxCNp3SqgdzpzThfWZEAqWak=
