sudo: false
services:
  - redis-server
language: scala
scala:
- 2.11.12
- 2.12.4
script:
- sbt ++$TRAVIS_SCALA_VERSION test
jdk:
- oraclejdk8
before_install:
- if [ $TRAVIS_PULL_REQUEST = 'false' ]; then
    openssl aes-256-cbc -K $encrypted_ff9678f33741_key -iv $encrypted_ff9678f33741_iv -in travis/secrets.tar.enc -out travis/local.secrets.tar -d;
    tar xv -C travis -f travis/secrets.tar;
  fi
after_success:
  - if [ $TRAVIS_PULL_REQUEST = 'false' ]; then
      sbt ++$TRAVIS_SCALA_VERSION releaseEarly;
    fi
deploy:
  on:
    tags: true
env:
  global:
  - secure: TBNoQkd7TUJksC3iCNtGFp3HNLQFkSldyoqU84T9XbxC07iluOC219LQnevQ6oGzngvJgteUT/1WR+WMTbrLKh+Xti0IwMYTbxPsOIA4FMKEqMbYfNdUJdrBmGExvJYX6uUCefVI85UWCeB8rFcHYTTXlyLvVUWkHljG6Wdk4Y8xIwfhs7Y/CF8s7RTsy/ellhvFEGtQgOPIXk2QP1VKEloFkI4N44EPYjT52ea6Ih4Z60pJYQE01Rt9ZmNmbFt06qe7IWiyyn6iPoEv+ZaSOgIsDCbwT7EEQhTv00KQr0Zsj1g80NSB3S+wkm+5dhA0zn5An8UjCgSPkuI6BLyzjDaMvUcKsBhZIyxLlsL38XmrncVg06yT4BA5KVsWJCZlgGIPiJk8NfDbHXBJDUMwf4mn/y2eTuE6odt1X1aGy7PpvC96yOnrpM7jVEoV7aEMjntuWXfHUQyrUs3zT9qIycIlZAF72PyaaY+oAAqonw+4nEqAWKgPE7mJt5VXGXGg8r/5c1mndD9LiO08THCQDZ/ZS0c2a6IGdho20+5HL1vsxSFJpLz+tEW7AYs1vjofs3lMeInVR/dvJHfwpsoxAEXxsafqZVS6492oN7vcHtbqT3VKMpqheySViECG42/J66UFzaCxwTCHJpZ2IDGozJuGmC8BIb3i40UgulVLxg8=
  - secure: eiAa6xuP1sC11rVbwdyiNbv9qiceRMRGhPUCM75DqcXU6zK7gQ72ioz4Bl8Zl7H8ZsCIVUJ6YFyCh6Mr+cXIl02285SjbiPekKiNSqGUbkFLad2pzsN3fONOqwOCJjFDOwnVZFxSklDmIj/nz0v0c5sq3AKtXSB0yDd2OIxNnE9LiGT1tWwp4sgXs6dr848mNX05csMYSlmHwsrDYqBApXBV0h9yVS9Zxr0p9uGzhakS/LksAhRxPuf4tvFTWb4MrFh7yuz86Z74wVyobr6ceUtLohTaz2uN6vqNRoYNqawkVGfxYRcyLVMq8InNen/+Z3dcnhCGk7mg8DB2YAvgMD7qvU1UKtTP1pjBIM8EREmUMVuvpfXOCE9ZlwVAad3j/15YBzVz/8GjRYZNXugf4m6MsFPBceVNs46417oqN7BnBmPsKtamX92xAtQMlSmtB/UbQa8NwKsXezn0jjAGdqxQjWwIe5JsqMfyYRNF5PlfzOLyqVTiMTitNAbD9NeTCsP3uLzFopihURZSGbzCe1g6AmuuYOSjeGQ0zG3x06/+O+SWfWHZ5c+jHO1BD31YOgCrOW2339+7oo0LbB4g/VxNl2TbG5GY5uGnBsd45qjr3Gp2hS6YSU1wYg8d2EuJxPNUXyJAK+CHbou9gcDNlJ9cNh0q8pkoSSaniFEy5RU=
  - secure: F3wrT+s3ghUp6jEkdiM/tT4V3tPGEwlefqhptfUckQEYZ7wHU9tzJlItdOqiU59anacJGcuYa1xY+0h4UpSkKyhVaNC8aQxXm0YSXuz2T5TE/0CoiM1HpPDlkRzOOLiTRbcOFWhxIwKgWqk4v0ly6ikryB43iv1JCu4JKoEFsxzw+57CLItj85Wu54TcIOf0IbuFgINSGkBnANEX8QHzWqVcHX1ooPAB1rJuKMQaIZDBNIR282Zmehd+zwMiXsHfm+T6HGMakKxejjcU69VWwSXZ4iekN1nDMvDVTQ1qJ6aryy38vip7t5yBGoNRnn8jxf84vv8PxqP8eK6MeHMpdenpXu0qInHH2n8zKcHGUimPYlKk+kFNhulxQCTfQew4jMggiEh2eSfqL6Ctjff5lGe9g5lgv6r7K3Vpe1ZvaDJ+fHrbc0QeZ8nMETAde9PGHz2UGJX4Fi1RqlvhC1NZpGXjePWAl5ixfA5gxO2sOrY1dB6viRIpVA5OaLVSpCk3Ehls4QqfgblAIjnfieLAFkWx8hfrmWW1HugtxOl47uMugIV1bqZxsBliO0Rbnyl0nA3jBXLQ4CPRyZafJxYwQ0B6olE/wJpQ3lHxNIN95hG7DkmG47JhQn+0dlplChAd0Tz1xQYaflNEl6po1RNAvkV6Tq9f6KH16FZXRxNKECE=
  - secure: UEk+FNJGff6jRxcATPWoJwdMMxmkWWmHyyMXKQXj1kymriZOah7JZBr6DCHVFaIT5YZF9BRNWuIlhProLOS5eJRGD/BUqbrmF6e1r9rN59K3RkK+gXbFllsyXStryNQYcq9dhxCMJKFV2GJbNJKthUAhhGZVVFFV/wC/BGcfGZqtEBsCZGEoJN8h1PQNdPUUYxnME/mFQW50Wvy09NB6N/ACkCgcJg3UVYh2NxcSfudEXEAOoQ86LDnK7ft/MsSW4LqqW5KeoaV5BJb24TWYIurugF9GdDREmBhqc7MPQGavAIumcnH6Gyl0aMWpt2XjlUSAzNi0RJkeus6J2wSJ+WOFpJcglbfgIxrsIi6d7rV5IKTNHZBxoaiXViGWBn3gT0z9QfLIM1Vnh2kDFqV0VXRBgnd8GFESzrrBZoPYsWwr/JAgDe7FYt8igItHhFj7Iuv8BYzmYhA896pC+zRIpo6V9od3on3JYqctS26R0cT8NlNPJGmULmn6Cw/eompYK33F1D43XxGKiYZ3RxbR7lpqoZsQoMYsRH+r0MFwDbpCurNHgAfvOyJdPJi0BG58IizxyYlgvwgzYqusa21mlWRi1tP9OU1ug9Z44HXETCp636xpme6zO1Hc4O+NE7kvGdLEGVc2aDx5CkJYUHjo3+Q4uJG3tKGUvdg4ascnYVg=
